/**
 * Guru Granites — photo registry.
 *
 * ── HOW TO ADD YOUR STONE PHOTOS ──────────────────────────────
 * A stone can show 1 or several photos (a swipeable gallery on the
 * product page, and one of them used as its thumbnail elsewhere).
 * 1. Drop the image(s) into  assets/stones/   (e.g. assets/stones/tan-brown-1.jpg)
 * 2. Add one line to `productPhotos` below, keyed by the stone's slug:
 *        'tan-brown': [
 *          require('../assets/stones/tan-brown-1.jpg'),
 *          require('../assets/stones/tan-brown-2.jpg'),
 *        ],
 *
 * ── HOW TO ADD "SEE IN SPACES" PHOTOS ─────────────────────────
 * These are the 3 photos of the stone installed in real spaces —
 * kitchen, flooring, cladding and so on — shown in the carousel.
 * 1. Drop them into  assets/spaces/
 * 2. Add one line to `spacePhotos`, keyed by the same slug:
 *        'tan-brown': [
 *          require('../assets/spaces/tan-brown-kitchen.jpg'),
 *          require('../assets/spaces/tan-brown-floor.jpg'),
 *          require('../assets/spaces/tan-brown-wall.jpg'),
 *        ],
 *
 * Stones with no entry fall back to a styled placeholder, so the app
 * always runs — you can add photos a few at a time.
 * ──────────────────────────────────────────────────────────────
 */

import type { ImageSourcePropType } from 'react-native';

import { productsByCategory, type CategoryKey } from './products';

/** Slug → one or more slab photos, shown as a swipeable gallery. */
// Generated by `node scripts/sync-photos.mjs` from the files in assets/stones/.
// Edit by adding or removing files there, then re-running that script.
export const productPhotos: Record<string, ImageSourcePropType[]> = {
  // <generated:product-photos>
  'alaska-pink': [require('../assets/stones/alaska-pink-1.jpg')],
  'alaska-white': [require('../assets/stones/alaska-white-1.jpg')],
  'aqua-green': [require('../assets/stones/aqua-green-1.jpg')],
  'asian-green': [require('../assets/stones/asian-green-1.jpg')],
  'asian-top': [require('../assets/stones/asian-top-1.jpg')],
  'astoria': [require('../assets/stones/astoria-1.jpg')],
  'bagera-black': [require('../assets/stones/bagera-black-1.jpg')],
  'beige-castle': [require('../assets/stones/beige-castle-1.jpg')],
  'black-galaxy-big-flower': [require('../assets/stones/black-galaxy-big-flower-1.jpg')],
  'black-galaxy-small-flower': [require('../assets/stones/black-galaxy-small-flower-1.jpg')],
  'black-marquino': [require('../assets/stones/black-marquino-1.jpg')],
  'black-pearl': [require('../assets/stones/black-pearl-1.jpg')],
  'black-rose': [require('../assets/stones/black-rose-1.jpg')],
  'blue-in-the-night': [require('../assets/stones/blue-in-the-night-1.jpg')],
  'boss-paradise': [require('../assets/stones/boss-paradise-1.jpg')],
  'burgundy-white': [require('../assets/stones/burgundy-white-1.jpg')],
  'cats-eye': [require('../assets/stones/cats-eye-1.jpg')],
  'cats-eye-brown': [require('../assets/stones/cats-eye-brown-1.jpg')],
  'charcoal-grey': [require('../assets/stones/charcoal-grey-1.jpg')],
  'cheetah-brown': [require('../assets/stones/cheetah-brown-1.jpg')],
  'chida-white': [require('../assets/stones/chida-white-1.jpg')],
  'china-white': [require('../assets/stones/china-white-1.jpg')],
  'coin-black': [require('../assets/stones/coin-black-1.jpg')],
  'colombo': [require('../assets/stones/colombo-1.jpg')],
  'colonial-gold': [require('../assets/stones/colonial-gold-1.jpg')],
  'crystal-blue': [require('../assets/stones/crystal-blue-1.jpg')],
  'deep-blue': [require('../assets/stones/deep-blue-1.jpg')],
  'diamond-black': [require('../assets/stones/diamond-black-1.jpg')],
  'diana-white': [require('../assets/stones/diana-white-1.jpg')],
  'emerald-marble': [require('../assets/stones/emerald-marble-1.jpg')],
  'era-white': [require('../assets/stones/era-white-1.jpg')],
  'fantasy-white': [require('../assets/stones/fantasy-white-1.jpg')],
  'gelatic-white': [require('../assets/stones/gelatic-white-1.jpg')],
  'gold-dust': [require('../assets/stones/gold-dust-1.jpg')],
  'golden-forest': [require('../assets/stones/golden-forest-1.jpg')],
  'green-marble': [require('../assets/stones/green-marble-1.jpg')],
  'green-sparkle': [require('../assets/stones/green-sparkle-1.jpg')],
  'hassan-green': [require('../assets/stones/hassan-green-1.jpg')],
  'himalayan-brown': [require('../assets/stones/himalayan-brown-1.jpg')],
  'ice-white': [require('../assets/stones/ice-white-1.jpg')],
  'impala-black': [require('../assets/stones/impala-black-1.jpg')],
  'ivory-brown': [require('../assets/stones/ivory-brown-1.jpg')],
  'jaggery-gold': [require('../assets/stones/jaggery-gold-1.jpg')],
  'kingfisher-blue': [require('../assets/stones/kingfisher-blue-1.jpg')],
  'lakha-red': [require('../assets/stones/lakha-red-1.jpg')],
  'lavender': [require('../assets/stones/lavender-1.jpg')],
  'luxury-black': [require('../assets/stones/luxury-black-1.jpg')],
  'maharaja-white': [require('../assets/stones/maharaja-white-1.jpg')],
  'moon-white': [require('../assets/stones/moon-white-1.jpg')],
  'multi-red': [require('../assets/stones/multi-red-1.jpg')],
  'navy-green-waterfall': [require('../assets/stones/navy-green-waterfall-1.jpg')],
  'parvati-white': [require('../assets/stones/parvati-white-1.jpg')],
  'peacock-green': [require('../assets/stones/peacock-green-1.jpg')],
  'pebbles': [require('../assets/stones/pebbles-1.jpg')],
  'river-black': [require('../assets/stones/river-black-1.jpg')],
  'river-white': [require('../assets/stones/river-white-1.jpg')],
  'riviera': [require('../assets/stones/riviera-1.jpg')],
  'romantic-blue': [require('../assets/stones/romantic-blue-1.jpg')],
  'scorpio-brown': [require('../assets/stones/scorpio-brown-1.jpg')],
  'shiva-gold': [require('../assets/stones/shiva-gold-1.jpg')],
  'sk-blue': [require('../assets/stones/sk-blue-1.jpg')],
  'snow-white': [require('../assets/stones/snow-white-1.jpg')],
  'star-white': [require('../assets/stones/star-white-1.jpg')],
  'steel-grey': [require('../assets/stones/steel-grey-1.jpg')],
  'supreme-white': [require('../assets/stones/supreme-white-1.jpg')],
  'swan-rose': [require('../assets/stones/swan-rose-1.jpg')],
  'tan-brown': [require('../assets/stones/tan-brown-1.jpg')],
  'white-fantasy': [require('../assets/stones/white-fantasy-1.jpg')],
  'white-galaxy': [require('../assets/stones/white-galaxy-1.jpg')],
  'white-marble': [require('../assets/stones/white-marble-1.jpg')],
  'white-onyx': [require('../assets/stones/white-onyx-1.jpg')],
  'white-pearl': [require('../assets/stones/white-pearl-1.jpg')],
  'wooden': [require('../assets/stones/wooden-1.jpg')],
  // </generated:product-photos>
};

/** Slug → up to 3 photos of the stone applied in real spaces. */
export const spacePhotos: Record<string, ImageSourcePropType[]> = {
  // 'tan-brown': [
  //   require('../assets/spaces/tan-brown-kitchen.jpg'),
  //   require('../assets/spaces/tan-brown-floor.jpg'),
  //   require('../assets/spaces/tan-brown-wall.jpg'),
  // ],
};

export function getProductPhotos(slug: string): ImageSourcePropType[] {
  return productPhotos[slug] ?? [];
}

/** First available photo for a stone, used as its thumbnail in grids. */
export function getThumbnail(slug: string): ImageSourcePropType | undefined {
  return productPhotos[slug]?.[0];
}

export function getSpacePhotos(slug: string): ImageSourcePropType[] {
  return spacePhotos[slug] ?? [];
}

/** Up to 3 sample thumbnails for a category, used as a tile backdrop collage. */
export function getCategoryCollage(key: CategoryKey): ImageSourcePropType[] {
  const photos: ImageSourcePropType[] = [];
  for (const product of productsByCategory(key)) {
    const thumb = getThumbnail(product.slug);
    if (thumb) photos.push(thumb);
    if (photos.length === 3) break;
  }
  return photos;
}

/** Labels shown under each "In Spaces" carousel frame, in order. */
export const SPACE_LABELS = ['In a kitchen', 'As flooring', 'As cladding'] as const;
